# Generated by Django 2.2.3 on 2019-07-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HireApplications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hire',
            options={'verbose_name': 'Product for hire', 'verbose_name_plural': 'Hire Products'},
        ),
    ]
