# Generated by Django 2.2.3 on 2019-07-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery Photo', 'verbose_name_plural': 'Gallery Photos'},
        ),
    ]
