# Generated by Django 2.2.3 on 2019-07-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='myemail@gmail.com', max_length=100),
        ),
    ]
