# Generated by Django 2.2.3 on 2019-07-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog',
        ),
    ]
