# Generated by Django 2.2.3 on 2019-07-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
