# Generated by Django 2.2.3 on 2019-07-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_photo',
            field=models.ImageField(default='main photo', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
