# Generated by Django 2.2.3 on 2019-07-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_blog_blog_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Company Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
