# Generated by Django 2.2.3 on 2019-07-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HireCorporateSocial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hirecorporate',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Social and Corporate Events'},
        ),
    ]
